### ISSUE TITLE
WootingTwo support?

### ISSUE THREAD

**Issue by SandroGrzicic** [microdee/WootingPiano#1]
Any plans for WootingTwo support? I tried it with my Wooting Two and it doesn't seem to work; I have a "red box" next to HID Status. Thanks!

**Comment by SandroGrzicic** [comment]
I can see that the [fork ](https://github.com/simon-wh/WootingPiano) seems to have WootingTwo support.

**Comment by microdee** [comment]
yeah that fork is the one converted to the official wooting sdk instead of pure HID. It's also used for an sdk example afaik
