### ISSUE TITLE
HID Status RED

### ISSUE THREAD

**Issue by vincentvandercruyssen** [microdee/WootingPiano#2]
Hi 
I just got the wooting two keyboard. I updated to the most recent SDK, installed loopMIDI and WootingPiano 0.2
Wooting Piano does not seem to be showing an activated HID Status and not recording any keystrokes.

![image](https://user-images.githubusercontent.com/27077333/91743022-7a341e80-ebb7-11ea-8183-cd00679b9bea.png)

Thanks for your help

**Comment by microdee** [comment]
Have you tried the Wooting dev's (Simon's) fork? https://github.com/simon-wh/WootingPiano

**Comment by vincentvandercruyssen** [comment]
Thanks, that works!
